steps:
- name: 'ubuntu'
  script: |
    #!/usr/bin/env bash
    wget -qO- https://firebase.tools | bash
- name: 'node'
  entrypoint: 'npm'
  args: ['install']
  dir: 'frontend'
- name: 'node'
  entrypoint: 'npm'
  args: ['run', 'build']
  dir: 'frontend'
options:
  logging: CLOUD_LOGGING_ONLY
