steps:
- name: 'node'
  entrypoint: 'npm'
  args: ['install', '-g', 'firebase-tools']
  dir: 'frontend'
- name: 'node'
  entrypoint: 'npm'
  args: ['install']
  dir: 'frontend'
- name: 'node'
  entrypoint: 'npm'
  args: ['run', 'build']
  dir: 'frontend'
options:
  logging: CLOUD_LOGGING_ONLY
