steps:
- name: 'node'
  entrypoint: 'npm'
  args: ['install']
  dir: 'frontend'
- name: 'node'
  entrypoint: 'npm'
  args: ['run', 'build']
  dir: 'frontend'
- name: '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/builder/firebase'
  args: ['deploy', '--only', 'hosting']
options:
  logging: CLOUD_LOGGING_ONLY
