steps:
- name: 'ubuntu'
  entrypoint: 'bash'
  args: ['curl', '-sL', 'https://firebase.tools', '|', 'bash']
- name: 'node'
  entrypoint: 'npm'
  args: ['install']
  dir: 'frontend'
- name: 'node'
  entrypoint: 'npm'
  args: ['run', 'build']
  dir: 'frontend'
