steps:
- name: 'node'
  entrypoint: 'npm'
  args: ['install']
  dir: 'frontend'
- name: 'node'
  entrypoint: 'npm'
  args: ['run', 'build']
  dir: 'frontend'
- name: 'node'
  script: |
    #!/usr/bin/env bash
    npm install -g firebase-tools
    firebase use --add $PROJECT_ID
    firebase deploy --only hosting
options:
  logging: CLOUD_LOGGING_ONLY
