steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['secrets', 'versions', 'access', 'latest', '--secret', 'terraform_tfvars', '--out-file', 'terraform.tfvars']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://${PROJECT_ID}-tfstate/terraform.tfstate', 'terraform.tfstate']
- name: 'hashicorp/terraform:light'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    terraform init
    terraform apply -auto-approve
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'terraform.tfstate', 'gs://${PROJECT_ID}-tfstate/terraform.tfstate']

options:
  logging: CLOUD_LOGGING_ONLY
