steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['secrets', 'versions', 'access', 'latest', '--secret', 'backend_config_secret', '--out-file', 'backend/config.toml']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
          '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/backend/${_SERVICE_NAME}:${SHORT_SHA}', 'backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/backend/${_SERVICE_NAME}:${SHORT_SHA}']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', '${_SERVICE_NAME}',
         '--image=${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/backend/${_SERVICE_NAME}:${SHORT_SHA}',
         '--region', '${_LOCATION}',
         '--platform', 'managed',
         '--allow-unauthenticated']
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - ${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/backend/${_SERVICE_NAME}:${SHORT_SHA}
