[tool.black]
line-length = 120
target-version = ["py312"]

[tool.isort]
profile = "black"

[tool.pydocstyle]
inherit = false
ignore = "D100,D104,D203,D212"
match = ".*\\.py"

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
strict = true

[[tool.mypy.overrides]]
module = "openai"
ignore_missing_imports = true
